name: remarked_online_chat
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^1.2.0
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  emoji_picker_flutter: ^1.6.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: